#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me www.linkedin.com/in/safa-miloud-799197264 permanent;' /etc/nginx/sites-available/default
sudo systemctl restart nginx
