#!/usr/bin/env bash
# have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!'  | sudo tee /var/www/html/index.html > /dev/null
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=swr7eq8Gdwc permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
