#!/usr/bin/env bash                    
# Fix Nginx listening on port 80

#remove the default nginx configuration file 
rm /etc/nginx/sites-enabled/default
# configure nginx to listen on port 80 of all the server’s active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
