#!/usr/bin/env bash                    
# Fix Nginx listening on port 80

#creates a symbolic link between the  nginx configuration file and enabled sites dir 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
#terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
