#!/usr/bin/env bash
#cript that displays Best School 10 times

#for the 9th iteration, displays Best School and then Hi on a new line

occ=0

while [ $occ -lt 10 ]
do
	if [ $occ -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( occ++ ))
done
