#!/usr/bin/env bash
#script that loops from 1 to 10
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
occ=0

while [ $occ -lt 10 ]
do
        if [ $occ -eq 3 ]
	then
		echo "bad luck"
	elif [ $occ -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( occ++ ))
done
