#!/usr/bin/env bash
# Bash script that displays:
# Displays the contents of the current dir in list format
# only displays the part of the name after the first dash

list=$(ls)
for i in $list; do

	echo "$i" | cut -d '-' -f2
done
