#!/usr/bin/env bash
# container so that Nginx is running as the nginx user
sed -i 's/^user .*$/user nginx nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx start
